### ISSUE TITLE
Broadlink and Samsung Smart TV inegrations

### ISSUE THREAD

**Issue by Drtatom** [AlexxIT/HassWP#20]
Hi, Alex

I'm having troubles with the las release HassWP_2021.6.5 when I try to install Broadlink and Samsung Smart TV integrations.

This is the errror that I get
2021-07-29 11:12:25 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of broadlink==0.17.0
2021-07-29 11:12:38 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration broadlink: No module named 'aiodiscover'
2021-07-29 11:20:04 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration samsungtv: No module named 'aiodiscover'

I´ve tried in two different PC and I get the same error. This only happen with the last release HassWP_2021.6.5. 
It works OK with the previous HassWP_2021.1.1.

Thank you!!

**Comment by nirgomer1** [comment]
Same issue here, when trying to add the Broadlink integration - getting the following error:
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration broadlink: No module named 'aiodiscover'

If I tried to pip-m install aiodiscover and then retry the broadlink integration - getting a different error:
cannot import name 'AF_UNIX' from 'socket'
Nothing I did (even trying to change socket.py to use AF_INET as suggested on the web) helped.

**Comment by nirgomer1** [comment]
any update? confirmation that this is an issue that can be resolved?

**Comment by jorbig** [comment]
The latest release (v2022.2.3) broke my Broadlink and Yeelight integrations, when I try to add them again, I get the error that "Config flow could not be loaded: [object Object]".

**Comment by AlexxIT** [comment]
Try latest release. Maybe it will help
https://github.com/AlexxIT/HassWP/releases/tag/v2022.5.3

**Comment by jorbig** [comment]
The latest release fixed it, thank you very much!
